# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RentalApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RentalApp
  pod 'Stripe'
  pod 'AWSS3'
  pod 'AWSCognito'
  pod 'AWSCore'

  target 'RentalAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RentalAppUITests' do
    # Pods for testing
  end

end
